language: swift	
	osx_image: xcode10.1
	branches:
	only:
	- main
	before_install:
	- gem install fastlane --no-ri --no-rdoc --no-document
	install: true
	script:
	- fastlane scan --scheme ReferenceiOS --device "iPhone XR"
